Repository HimanshuNarware/Devlabs, pull requests merged in 2024-06, with the labels that each got.

#594 Closing button was not there in chatbot
  frontend/src/ChatAssistant/ChatAssistant.css
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/style/Home.css
Labels: enhancement, level2, gssoc, Advanced

#593 fixed scroll to top on render of new page
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.css
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/ScrollToTop.jsx
  frontend/src/index.css
  frontend/src/index.js
Labels: level2, gssoc, Advanced

#589 Toast
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/BookMark.js
  frontend/src/Component/Home.js
Labels: level2, gssoc, Advanced

#598 back to top button done
  frontend/src/Component/BackToTopButton.js
  frontend/src/Component/Home.js
Labels: enhancement, level2, Advanced

#445 [FEAT]: Created Issue forms and made the issue options more visually appealing
  .github/ISSUE_TEMPLATE/adding-new-tool.md
  .github/ISSUE_TEMPLATE/adding-new-tool.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation-issue.md
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement, level3, gssoc

#615 Added contact button to navbar and also fixed few errors in other codes
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.css
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/Navbar/NavbarCenter.js
Labels: enhancement, level2, gssoc, Advanced

#603 Footer links
  frontend/src/App.js
  frontend/src/Component/Footer.js
  frontend/src/pages/AI.jsx
  frontend/src/pages/CodingPlateform.jsx
  frontend/src/pages/CourcesPlatform.jsx
  frontend/src/pages/EthicalHacking.jsx
  frontend/src/pages/Extension.jsx
  frontend/src/pages/FrontendTools.jsx
  frontend/src/pages/Movie.jsx
  frontend/src/pages/RemoteJobs.jsx
  frontend/src/pages/UI.jsx
Labels: level2, gssoc, Advanced

#601 Added FAQ Page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.css
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/Faq.js
  frontend/src/Component/Navbar/NavbarCenter.js
  frontend/src/Component/accordion.js
  frontend/src/style/faq.css
Labels: enhancement, level2, gssoc, Advanced

#602 Made several changes and added email pattern verification
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.css
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/Footer.js
  frontend/src/Component/Review.js
  frontend/src/index.js
  frontend/src/style/Review.css
Labels: enhancement, level2, gssoc, Advanced

#605 added contributor secton
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.css
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/Home.js
  frontend/src/style/Home.css
Labels: enhancement, level2, gssoc, Advanced

#654 Fixed images not visible in some browsers
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#649 Created_candi_page
  frontend/src/Component/Navbar/NavbarItem.js
Labels: enhancement, level2, gssoc, Advanced

#639 Cleared all the code bugs and also completed #629
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/Footer.js
  frontend/src/index.js
  frontend/src/pages/CodingPlateform.jsx
  frontend/src/pages/CodingPlatform.jsx
  frontend/src/pages/CoursesPlatform.jsx
  frontend/src/pages/Extension.jsx
Labels: enhancement, level2, dwoc, Advanced

#687 Added Rate Us Option
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/Footer.js
  frontend/src/Component/Modal.js
  frontend/src/Component/Navbar/NavbarCenter.js
  frontend/src/Component/Rateus.js
  frontend/src/index.js
  frontend/src/pages/CodingPlatform.jsx
  frontend/src/style/Modal.css
  frontend/src/style/Navbar.css
  frontend/src/style/Rateus.css
Labels: enhancement, level2, gssoc, Advanced

#698 Footer content layout change
  frontend/src/Component/Footer.js
Labels: enhancement, level2, gssoc, Advanced

#696 Webflow web designing tool
  frontend/public/webflow.jpg
  frontend/src/DB/product.json
Labels: enhancement, level2, gssoc, Advanced

#684 Frontned tools page
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/Footer.js
  frontend/src/Component/Sidebar/Sidebar.js
  frontend/src/index.js
  frontend/src/pages/CodingPlateform.jsx
  frontend/src/pages/Collaboration.jsx
  frontend/src/pages/Extension.jsx
  frontend/src/pages/FrontendTools.jsx
  frontend/src/pages/Productivity.jsx
  frontend/src/style/FrontendTools.css
Labels: enhancement, level2, gssoc, Advanced

#701 elements of the navbar are aligned properly in a single row
  frontend/src/style/Navbar.css
Labels: enhancement, level2, gssoc, Advanced

#694 Fix and Enhance Project Management API: Typo Correction, Validation, and Pagination
  backend/src/controllers/openSourceController.js
Labels: enhancement, level1, gssoc, Advanced

#692 Added Hover effect Successfully
  frontend/package-lock.json
  frontend/package.json
  frontend/src/style/Home.css
Labels: enhancement, level2, gssoc, Advanced

#631 Burger menu links
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/Footer.js
  frontend/src/index.js
Labels: enhancement, level2, gssoc, Advanced

#638 Email Validation Done
  backend/src/app.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/Footer.js
  frontend/src/Component/Review.js
  frontend/src/index.js
Labels: enhancement, level2, gssoc, Advanced

#658 An AI copywriting tool
  frontend/public/copy-ai.jpg
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#666 Added edX Tool and Fixed Some Bugs
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/Footer.js
  frontend/src/DB/product.json
  frontend/src/index.js
Labels: level2, gssoc, Advanced

#716 modify about
  frontend/src/Component/Home.js
  frontend/src/style/About.css
Labels: enhancement, level2, gssoc, Advanced

#703 added coding plateform page
  frontend/src/pages/CodingPlateform.jsx
  frontend/src/style/CodingPlateform.css
Labels: level2, gssoc, Advanced

#761 Fixed import issues and other syntax issues that wouldn't allow the frontend server to start properly
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/Footer.js
  frontend/src/index.js
Labels: enhancement, level2, gssoc, Advanced

#741 Added Toastify Message
  frontend/src/Component/Rateus.js
Labels: level2, gssoc, Advanced

#731 Ethical hacking
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/Footer.js
  frontend/src/index.js
  frontend/src/pages/CodingPlatform.jsx
  frontend/src/pages/EthicalHacking.jsx
  frontend/src/style/EthicalHacking.css
Labels: level2, gssoc, Advanced

#718 Adding search bar to contribution page
  frontend/src/Component/About.js
  frontend/src/style/About.css
Labels: enhancement, level2, gssoc, Advanced

#792 Changed the website name and fixed App.js
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.jsx
Labels: enhancement, level3, gssoc, Advanced

#675 description text bug fixed
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/BookMark.js
  frontend/src/Component/Footer.js
  frontend/src/index.js
  frontend/src/style/BookMark.css
Labels: enhancement, level2, gssoc, Advanced

#780 [Feature Request]: Create Cource Plateform Page
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/index.css
  frontend/src/pages/CoursesPlatform.jsx
  frontend/src/style/Courses.css
Labels: enhancement, level3, gssoc, Advanced

#845 Added containerization files for both frontend and backend
  backend/.dockerignore
  backend/Dockerfile
  compose.yaml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/src/App.js
  frontend/src/ChatAssistant/Avatar.jsx
  frontend/src/ChatAssistant/UserAvatar.jsx
  frontend/src/Component/About.js
  frontend/src/Component/Footer.js
  frontend/src/index.js
Labels: level2, gssoc, Advanced

#844 Fixed input of chatbox
  frontend/src/ChatAssistant/ChatAssistant.css
Labels: level1, gssoc, Advanced

#841 Filled Remote jobs section
  frontend/src/App.js
  frontend/src/index.js
  frontend/src/pages/RemoteJobs.jsx
  frontend/src/style/RemoteJobs.css
Labels: level2, gssoc, Advanced

#846 Removed Unnecessary Footer
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/Component/Footer.js
  frontend/src/index.css
  frontend/src/index.js
Labels: level2, gssoc, Advanced

#832 Icon finder
  frontend/src/App.js
  frontend/src/Component/Footer.js
  frontend/src/DB/product.json
  frontend/src/index.js
Labels: level2, Advanced

#830 Framer motion
  frontend/src/App.js
  frontend/src/Component/Footer.js
  frontend/src/DB/product.json
  frontend/src/index.js
Labels: level2, gssoc, Advanced

#854 Enhanced Navbar and Removed Repeated Content
  frontend/src/App.js
  frontend/src/index.js
  frontend/src/style/Courses.css
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#874 Responsive ui
  frontend/src/Component/Navbar/Navbar.js
  frontend/src/DB/product.json
  frontend/src/index.js
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#894 Update Footer.js
  frontend/src/Component/Footer.js
Labels: level1, gssoc, Advanced

#863 added magicui
  frontend/src/DB/product.json
Labels: level2

#861 added takeUforward
  frontend/src/DB/product.json
Labels: level2, gssoc

#859 added coding ninjas and fixed one bug
  frontend/src/DB/product.json
Labels: level2, gssoc

#860 added copilot-ai
  frontend/src/DB/product.json
Labels: level2, gssoc

#897 Upadted README.md replacing Devlaps into Devlabs
  README.md
  frontend/src/Component/Footer.js
  frontend/src/image/logo.png
  frontend/src/style/Footer.css
  frontend/src/style/Navbar.css
Labels: level1, gssoc, Advanced

#866 Minor_changes - Footer Duplicate - Minor Fixes
  frontend/src/App.js
  frontend/src/Component/Footer.js
  frontend/src/DB/product.json
  frontend/src/pages/CodingPlatform.jsx
  frontend/src/style/CodingPlatform.css
Labels: level1, gssoc, Advanced

#947 Modify about
  frontend/src/index.js
Labels: level2, gssoc, Advanced

#910 replace logo Devlaps to Devlabs and fix the footer and fix the search bar
  frontend/src/Component/Footer.js
  frontend/src/Component/Navbar/NavbarLeft.js
  frontend/src/image/logo1.png
  frontend/src/style/Footer.css
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#950 Update product.json
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#856 lighthouse tool added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#951 Modify Rate us
  frontend/src/style/Rateus.css
Labels: level2, gssoc, Advanced

#905 Coding
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#998 Add condition for pagination and also remove prev and next button for first and last page
  frontend/src/Component/About.js
  frontend/src/Component/Pagination.js
  frontend/src/utils/paginationData.js
Labels: level3, gssoc, Advanced

#992 Invideo Ai tool added to the project
  frontend/src/DB/product.json
Labels: enhancement, level2, gssoc, Advanced

#968 added the new tools and solved the issue
  frontend/public/docker_playground.png
  frontend/public/heroicon.png
  frontend/public/icons8.png
  frontend/public/react_icons.png
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#990 Feedback type
  frontend/src/Component/Review.js
Labels: level2, gssoc, Advanced

#1015 Resolved overlapping between chatbot and scroll-to-top button
  frontend/src/ChatAssistant/ChatAssistant.css
  node_modules/.package-lock.json
Labels: level2, gssoc, Advanced

#1011 Trailing cursor
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/ChatAssistant/ChatAssistant.css
  frontend/src/Component/TrailingCursor/TrailingCursor.jsx
  frontend/src/Component/TrailingCursor/TrailingCursor.module.css
  frontend/src/index.css
  frontend/src/style/About.css
  frontend/src/style/BackToTopButton.css
  frontend/src/style/BookMark.css
  frontend/src/style/Footer.css
  frontend/src/style/Home.css
  frontend/src/style/Modal.css
  frontend/src/style/Navbar.css
  frontend/src/style/NotFound.css
  frontend/src/style/Rateus.css
Labels: level2, gssoc, Advanced

#1008 careerflow ai extension added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#954 Seperate page for contact us
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/Component/Contact.jsx
  frontend/src/Component/Navbar/NavbarCenter.js
  frontend/src/style/Contact.css
Labels: level2, gssoc, Advanced

#960 Duplicate tools removed
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#966 Enhanced RateUs Option
  frontend/src/App.js
  frontend/src/Component/Rateus.js
  frontend/src/index.js
  frontend/src/style/Home.css
  frontend/src/style/Navbar.css
  frontend/src/style/Rateus.css
Labels: level2, gssoc, Advanced

#858 Update README.md #842
  README.md
Labels: level2, gssoc, Advanced

#1052 search box position fixed there relative position
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1048 Unique Key Prop in Sidebar
  frontend/src/Component/Sidebar/Sidebar.js
Labels: level2, gssoc, Advanced

#1044 programiz added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1039 gdb added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1046 Update product.json as per issue#368
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1038 docker added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1031 github copilot added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1036 Added Udemy
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1030 gemini added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1074 Update Remote Job Section
  frontend/public/gun-io.png
  frontend/public/toptal.webp
  frontend/public/turing.jpg
  frontend/public/x-team.jpg
  frontend/src/DB/product.json
  frontend/src/pages/RemoteJobs.jsx
  frontend/src/style/RemoteJobs.css
Labels: level2, gssoc, Advanced

#1073 Added over api cheet sheet
  frontend/src/DB/product.json
Labels: level3, gssoc, Advanced

#1068 Insta Hire
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1004 Next.js framework in FrontendTools page
  frontend/src/pages/FrontendTools.jsx
Labels: level2, gssoc, Advanced

#965 Added Hover Effect
  frontend/src/Component/Rateus.js
  frontend/src/style/Navbar.css
  frontend/src/style/Rateus.css
Labels: level2, gssoc, Advanced

#962 Added Acertinity UI Components Library
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1072 Added Relight image editing tool
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1071 Added I love img tool
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1066 Tool National library of India
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1108 Added tilt effect
  frontend/package.json
  frontend/src/Component/Home.js
Labels: level2, gssoc, Advanced

#1056 Tool Unsplash free stack visuals
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1058 Tool maths gpt
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1131 Added 3d card Effect
  frontend/src/style/Home.css
Labels: level2, gssoc, Advanced

#1121 add jasper ai
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1120 add vercelTool
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1132 Enhancement of coding platform page
  frontend/src/style/CodingPlatform.css
Labels: level2, gssoc, Advanced

#1118 add spline3d tool
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1127 added new tool and search bar into body
  frontend/package-lock.json
  frontend/src/Component/Home.js
  frontend/src/Component/Navbar/Navbar.js
  frontend/src/Component/Navbar/NavbarRight.js
  frontend/src/DB/product.json
  frontend/src/style/Home.css
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1141 Added Loading SKeleton
  frontend/package.json
  frontend/src/Component/Home.js
Labels: level2, gssoc, Advanced

#1125 ADD Bulma in front-end-tools
  frontend/src/pages/FrontendTools.jsx
Labels: level2, gssoc, Advanced

#1119 add aceternity ui
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1117 add adobeXd tool
  frontend/package-lock.json
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1070 Added Boootstrap tool
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1147 Added Foundation Tool
  frontend/src/pages/FrontendTools.jsx
Labels: level2, gssoc, Advanced

#1069 added infosys-springboard
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1067 added coderbyte
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1065 Added bright data tool
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1064 Added oh my git
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1057 Tool interview warmup by Google
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1166 Movies page
  frontend/package-lock.json
  frontend/src/pages/AI.jsx
  frontend/src/pages/Movie.jsx
  frontend/src/style/AI.css
  frontend/src/style/Movie.css
Labels: level2, gssoc, Advanced

#1171 [New Tool]: Want to Add Array Explorer #1137
  frontend/src/DB/product.json
Labels: level2, gssoc

#1169 added contribute here and other links
  frontend/src/Component/Footer.js
  frontend/src/Component/TrailingCursor/TrailingCursor.jsx
Labels: level2, gssoc, Advanced

#1164 Video Compressor added to project
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1162 Update README.md
  README.md
Labels: level2, gssoc, Advanced

#1159 Added CareerFlow Extension
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1158 Jenkins added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1179 contact form design
  frontend/src/Component/Contact.jsx
  frontend/src/DB/product.json
  frontend/src/lottie/contact.json
  frontend/src/style/Contact.css
Labels: level2, gssoc, Advanced

#1176 Newtool : Esaay flow tool added to project
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced
