Repository HimanshuNarware/Devlabs, pull requests merged in 2024-05, with the labels that each got.

#353 review-form store in backend
  backend/src/config/database.js
  backend/src/controllers/specialController.js
  backend/src/models/reviewForm.js
  frontend/package-lock.json
  frontend/package.json
Labels: hacktoberfest, level2, gssoc, Advanced

#351 added coursera website successfully #252
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#349 Rating System in Feedback Section #317
  frontend/src/Component/Rate.js
  frontend/src/Component/Review.js
Labels: enhancement, level2, gssoc, Advanced

#345 added Apidog API Testing and Documenting Tool
  frontend/public/Apidog.jpg
  frontend/src/DB/product.json
Labels: enhancement, level2, gssoc, Advanced

#342 Issue:331 - Added smooth hovering effects for cards.
  frontend/src/style/Home.css
Labels: level2, gssoc, Advanced

#341 Fixed search bar is not visible in the mobile view
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#340 Framer web designing tool
  frontend/public/framer.svg
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#330 Change font styling of Navbar and Footer
  frontend/package-lock.json
  frontend/public/index.html
  frontend/src/style/Footer.css
Labels: level1, gssoc, Advanced

#324 Made changes in About us page ui and fixed merge conflicts
  frontend/src/Component/About.js
  frontend/src/style/About.css
  package-lock.json
Labels: level2, gssoc, Advanced

#323 Added Hover Effects
  frontend/src/style/Footer.css
Labels: enhancement, level1, gssoc

#295 fix the card sizing in home page and bookmark page #279
  frontend/src/Component/Home.js
  frontend/src/style/BookMark.css
  frontend/src/style/Home.css
Labels: level2, gssoc, Advanced

#321 Redesign the Footer
  frontend/src/Component/Footer.js
  frontend/src/Component/Sidebar/Sidebar.js
  frontend/src/style/Footer.css
Labels: level1, gssoc, Advanced

#371 Feature added : Home screen update on typing in the search bar
  .idea/.gitignore
  .idea/Devlabs.iml
  .idea/modules.xml
  .idea/vcs.xml
  frontend/package-lock.json
  frontend/src/Component/Home.js
  frontend/src/style/About.css
  frontend/src/style/Footer.css
Labels: level2, gssoc, Advanced

#359 Added whimsical in products
  frontend/src/DB/product.json
  frontend/src/style/About.css
  frontend/src/style/Footer.css
Labels: level2, gssoc

#406 #363 solved - added dark mode toggle on top right of page
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/style/Footer.css
Labels: level2, gssoc, Advanced

#391 Changed the text area.
  frontend/src/style/Review.css
Labels: level1, gssoc

#400 Proper Padding to buttons
  frontend/src/style/About.css
  frontend/src/style/Pagination.css
Labels: level1, gssoc, Advanced

#398 updated about
  frontend/package-lock.json
  frontend/src/Component/About.js
  frontend/src/style/About.css
Labels: hacktoberfest, level2, gssoc

#421 fix issue :Footer social icons not visible
  frontend/src/Component/Footer.js
Labels: hacktoberfest, level2, gssoc

#416 SpinBot AI Tool
  frontend/public/spinbot.png
  frontend/src/DB/product.json
Labels: enhancement, level2, gssoc, Advanced

#439 Fix: Footer section is not working properly in Dark Mode and Light Mode
  frontend/src/index.js
  frontend/src/style/Footer.css
  frontend/src/style/Navbar.css
Labels: level3, gssoc, Advanced

#434 Modify search bar
  frontend/src/Component/Navbar/NavbarRight.js
  frontend/src/style/Navbar.css
Labels: level1, gssoc, Advanced

#430 updated hero_img
  frontend/src/Component/Home.js
  frontend/src/image/hero_img.svg
  frontend/src/style/Home.css
Labels: level2, gssoc, Advanced

#456 Updated get started button
  frontend/src/style/Home.css
  frontend/src/style/Navbar.css
Labels: hacktoberfest, level2, gssoc

#455 UI issue is fixed in about us section
  frontend/src/Component/About.js
  frontend/src/style/About.css
Labels: level2, gssoc, Advanced

#449 Added discord
  backend/package.json
  backend/src/models/Tool.js
  frontend/src/Component/Sidebar/Sidebar.js
  frontend/src/DB/product.json
Labels: enhancement, level2, gssoc

#414 added workflow for closing old PRs
  .github/workflows/close-old-pr-woc.yml
Labels: enhancement, level2, Advanced

#491 Update Home.css
  frontend/src/style/Home.css
Labels: enhancement, level1

#481 Added new tools
  frontend/src/DB/product.json
Labels: level2, gssoc

#477 Adding Slidesgo
  frontend/package-lock.json
  frontend/public/slidesgo.png
  frontend/src/DB/product.json
Labels: enhancement, level2, Advanced

#427 added workflow as mentioned in the issue #408
  .github/workflows/close-on-merge.yml
Labels: level3, gssoc, Advanced

#476 Added draw.io to products
  frontend/public/drawio.jpg
  frontend/src/DB/product.json
Labels: enhancement, level2, gssoc, Advanced

#461 added hashnode
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#501 Add hover effect to booked card
  frontend/src/Component/Sidebar/Sidebar.js
  frontend/src/DB/product.json
  frontend/src/style/BookMark.css
  frontend/src/style/Home.css
Labels: level1, gssoc

#524 subscript_of_bookmark
  frontend/package-lock.json
  frontend/src/Component/Navbar/NavbarCenter.js
  frontend/src/Component/Navbar/NavbarItem.js
  frontend/src/Slice/DataSlice.js
  frontend/src/index.js
Labels: level2, gssoc, Advanced

#521 updated review page
  frontend/src/style/Review.css
Labels: level2, gssoc, Advanced

#518 Redirected social media links to a new tab
  frontend/src/Component/Footer.js
  frontend/src/style/Home.css
Labels: enhancement, level1, gssoc

#512 Add responsiveness in Hero section for All devices
  backend/package-lock.json
  backend/src/app.js
  frontend/src/Component/Home.js
  frontend/src/DB/product.json
  frontend/src/style/Home.css
Labels: enhancement, level2, gssoc, Advanced

#511 Style change
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/style/Navbar.css
Labels: enhancement, level2, gssoc, Advanced

#537 Changed outdated Twitter icon to updated version X.
  frontend/public/index.html
  frontend/src/Component/Footer.js
  frontend/src/style/Footer.css
Labels: enhancement, level1, gssoc, Advanced

#543 navbar color
  frontend/src/style/Navbar.css
Labels: enhancement, level1, gssoc, Advanced

#542 visibled bottom to top button
  frontend/src/style/BackToTopButton.css
Labels: enhancement, level1, gssoc, Advanced

#539 Add Directly removed Bookmark from HomePage and also show removed popUp when user removed bookMark
  frontend/src/Component/Home.js
  frontend/src/style/Home.css
Labels: level2, gssoc, Advanced

#482 Added a category name "Explore."
  frontend/src/Component/Footer.js
  frontend/src/style/Footer.css
Labels: enhancement, level2, gssoc, Advanced

#466 Corrected spelling mistake in Frontend.
  frontend/src/Component/Footer.js
Labels: enhancement, level2, Advanced

#550 Improved contrast of text in both themes
  frontend/src/style/NotFound.css
Labels: enhancement, level1, gssoc, Advanced

#549 Added new tool seowriting.ai
  frontend/src/DB/product.json
Labels: enhancement, level2, gssoc, Advanced

#505 added preloader
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Component/Preloader.js
  frontend/src/index.js
  frontend/src/lottie/pre.json
  frontend/src/style/preloader.css
Labels: enhancement, level2, Advanced

#450 Added the feature to auto comment on pr merged
  .github/workflows/auto-comment-on-pr-merge.yml
Labels: enhancement, level2, gssoc, Advanced

#508 Add new feature: enhancement the chat-bot feature
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/ChatBot/ActionProvider.jsx
  frontend/src/DB/product.json
Labels: enhancement, level2, gssoc, Advanced

#557 Animation on chatbot #551
  frontend/src/ChatAssistant/ChatAssistant.css
  frontend/src/ChatAssistant/ChatAssistant.jsx
Labels: enhancement, level1, gssoc, Advanced

#558 Hover effect for ChatBot logo on opening and closing
  frontend/src/ChatAssistant/ChatAssistant.css
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/assets/logo1.png
Labels: enhancement, level1, gssoc
