Repository HimanshuNarware/Devlabs, pull requests merged in 2024-07, with the labels that each got.

#1221 Sponsor me button added #614
  frontend/src/Component/Footer.js
Labels: level2, gssoc, Advanced

#1250 perplexity ai added
  frontend/src/DB/product.json
Labels: enhancement, level2, gssoc, Advanced

#1241 Removed the 404 error and added contents on the collaboration tools page.
  frontend/src/App.js
  frontend/src/pages/Collaboration.jsx
  frontend/src/style/Collaboration.css
Labels: level2, gssoc, Advanced

#1259 Added GSSoC
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1258 Google colab
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1257 Added Babbel
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1256 Added Linkedin learing
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1148 Enhanced Home Page
  frontend/src/Component/Navbar/Navbar.js
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1150 fixed hero section to be responsive
  frontend/src/Component/Home.js
  frontend/src/style/Home.css
Labels: level2, gssoc, Advanced

#1177 modal close with close icon as well when user click outside the modal…
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Component/Navbar/NavbarCenter.js
  frontend/src/Component/Rateus.js
  frontend/src/style/Modal.css
Labels: level2, gssoc, Advanced

#1186 Added MangaReader
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1255 Added Skill share
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1195 mlwbd added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1213 ADD Supply Chain Management DApp
  frontend/src/DB/openSource.json
Labels: level2, gssoc, Advanced

#1216 Issue No: #1111 Hover effects improved
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1272 Added contents on UI page.
  frontend/src/DB/product.json
  frontend/src/pages/UI.jsx
  frontend/src/style/UI.css
Labels: level2, gssoc, Advanced

#1254 Added Edabit
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1245 Added Video Downloader
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1244 runaway ai is added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1243 Fixed Devlabs heading is overlapping with sidebar
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1242 stability ai added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1290 [New Tool]: Adding Grommet tool in frontend Tools #1173
  frontend/src/pages/FrontendTools.jsx
Labels: level2, gssoc, Advanced

#1231 Update index.html
  frontend/public/index.html
Labels: level2, gssoc, Advanced

#1239 Removed the error and added contents on the productivity tools page.
  frontend/src/App.js
  frontend/src/pages/Productivity.jsx
  frontend/src/style/Productivity.css
Labels: level2, gssoc, Advanced

#1247 Fixed the navbar overflow of contents
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1226 Feature :Descrition and logo added
  frontend/src/Component/Footer.js
Labels: level2, gssoc, Advanced

#1275 Added Hover Effect to Footer Links
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/ChatBot/ActionProvider.jsx
  frontend/src/Component/Faq.js
  frontend/src/Component/Footer.js
  frontend/src/Component/Home.js
  frontend/src/Component/Navbar/NavbarLeft.js
  frontend/src/Component/Navbar/NavbarRight.js
Labels: level2, gssoc, Advanced

#1285 Added Bollyflix
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1282 Added HiAnime
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1278 Added forage
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1283 Added 123Movies
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1284 Added 1Flix
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1286 Added GitLab
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1287 Added Binged
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1289 Added Udemy to devlabs
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1297 Fixed background
  frontend/src/index.js
Labels: level2, gssoc, Advanced

#1313 [ IMP FEATURE ] Category sorting
  frontend/src/Component/Home.js
  frontend/src/style/Home.css
Labels: level3, gssoc, Advanced

#1325 forage added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1324 zoom added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1321 sharly added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1320 Leonardo AI added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1338 ADD petAdopt opensource
  frontend/src/DB/openSource.json
Labels: level2, gssoc, Advanced

#1337 added leetcode and codechef
  frontend/src/pages/CodingPlatform.jsx
Labels: level2, gssoc, Advanced

#1342 sass added
  frontend/src/pages/FrontendTools.jsx
Labels: level2, gssoc, Advanced

#1341 Warmer AI added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1340 Akkio AI added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1303 Sidebar missing links
  frontend/src/Component/Home.js
  frontend/src/Component/Sidebar/Sidebar.js
Labels: level2, gssoc, Advanced

#1280 Bem naming convention
  frontend/src/Component/About.js
  frontend/src/Component/BookMark.js
  frontend/src/Component/Faq.js
  frontend/src/Component/OpenSource.js
  frontend/src/Component/Rateus.js
  frontend/src/Component/Review.js
  frontend/src/style/About.css
  frontend/src/style/BookMark.css
  frontend/src/style/OpenSource.css
  frontend/src/style/Rateus.css
  frontend/src/style/Review.css
  frontend/src/style/faq.css
Labels: level2, gssoc, Advanced

#1230 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: level2, gssoc, Advanced

#1364 Added Quira
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1366 Added Quora digest
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1377 Made website responsive for alll devices
  frontend/src/Component/Faq.js
  frontend/src/index.css
  frontend/src/style/Home.css
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1372 Added new tool Brime to Bulk resize the images
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1379 back to top button
  frontend/src/style/BackToTopButton.css
Labels: level2, gssoc, Advanced

#1429 added SQL server in tools
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1428 email validation
  frontend/src/Component/Contact.jsx
Labels: level2, gssoc, Advanced

#1433 updated footer issue
  frontend/src/Component/Footer.js
  frontend/src/style/Footer.css
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1431 fixed issue #1344
  frontend/src/style/Navbar.css
Labels: level3, gssoc, Advanced

#1427 Added TypeScript as new tool on frontend-Tools
  frontend/src/pages/FrontendTools.jsx
Labels: level2, gssoc, Advanced

#1425 backcommit
  frontend/src/App.js
  frontend/src/Component/Sidebar/Sidebar.js
  frontend/src/pages/BackendTools.jsx
  frontend/src/style/BackendTools.css
Labels: level2, gssoc, Advanced

#1410 Added FlutterFlow into devlabs
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1412 Added Fotor into devlabs
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1409 Added SkillsNetwork Lab
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1407 Added Shutterstock
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1405 Added Animetsu
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1404 Added Listly - Web Scraping
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1400 add tooltip
  frontend/src/ChatAssistant/ChatAssistant.css
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/Component/BackToTopButton.js
  frontend/src/style/BackToTopButton.css
  frontend/src/style/tooltip.css
Labels: level2, gssoc, Advanced

#1393 Extension heading is now visible on the Extensions page.
  frontend/src/pages/Extension.jsx
Labels: level2, gssoc, Advanced

#1390 fiverr added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1389 antropic ai added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1388 deep ai added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1387 lucid chart added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1386 sublime text added
  frontend/src/DB/product.json
Labels: hacktoberfest, level2, gssoc, Advanced

#1385 clarif AI added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1383 cohere ai added
  frontend/src/DB/product.json
Labels: hacktoberfest, level2, gssoc, Advanced

#1382 Toast review form
  frontend/src/Component/Review.js
  frontend/src/pages/UI.jsx
  frontend/src/style/UI.css
Labels: level2, gssoc, Advanced

#1381 Added contents on the courses platform page and removed the 404 error page.
  frontend/src/Component/Sidebar/Sidebar.js
  frontend/src/pages/CoursesPlatform.jsx
Labels: level3, gssoc, Advanced

#1411 Updated product.json
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1343 NewTool : Coded pen added to project
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1292 [New Tool]: ADDING Ant Design Tool Frontend Tools #1172 #1291
  frontend/src/pages/FrontendTools.jsx
Labels: level2, gssoc, Advanced

#1461 Modify home page all issues
  frontend/src/Component/Footer.js
  frontend/src/Component/Home.js
  frontend/src/style/Footer.css
  frontend/src/style/Home.css
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1476 update review
  frontend/src/style/Review.css
Labels: level2, gssoc, Advanced

#1460 Corrected the contents of Movie & Series page.
  frontend/src/pages/Movie.jsx
Labels: level3, gssoc, Advanced

#1445 Update App.js
  frontend/src/App.js
Labels: level2, gssoc, Advanced

#1439 header hover effect updated
  frontend/package-lock.json
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1534 Efficiency Enhancement
  frontend/src/App.js
Labels: level2, gssoc, Advanced

#1538 Added Copilot in Extension
  frontend/src/pages/Extension.jsx
Labels: level2, gssoc, Advanced

#1440 Footer-Hover Updated
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1478 Added Research AI
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1479 modify opensource page and responsive also
  frontend/src/Component/OpenSource.js
  frontend/src/style/About.css
  frontend/src/style/OpenSource.css
Labels: level2, gssoc, Advanced

#1482 NewTool: Play Code Platform is added to the Project
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1484 hackerrank coding platform
  frontend/src/pages/CodingPlatform.jsx
Labels: level2, gssoc, Advanced

#1496 Contributor section design fixed
  frontend/src/Component/About.js
  frontend/src/style/About.css
Labels: level3, gssoc, Advanced

#1497 cursor issue
  frontend/src/index.css
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1499 [ IMP FEATURE ] : Search Bar Functionality
  frontend/src/Component/Home.js
  frontend/src/style/Home.css
Labels: level3, gssoc, Advanced

#1501 synthesia added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1502 descript ai added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1503 freelancer added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1559 Modify Contact Us page
  frontend/src/Component/Contact.jsx
  frontend/src/lottie/contact.json
  frontend/src/style/Contact.css
Labels: level2, gssoc, Advanced

#1558 Open Source page redesigned
  frontend/src/style/OpenSource.css
Labels: level2, gssoc, Advanced

#1562 Algomonster added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1561 Sphinx added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1573 added code avengers
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1597 Made contributor section responsive and also structured components of contributor section
  frontend/src/style/About.css
Labels: level2, gssoc, Advanced

#1504 learn git branching added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1505 goose ai added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1506 lovo ai added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1576 Create Typography.css
  frontend/src/style/Typography.css
Labels: level2, gssoc, Advanced

#1507 llama ai added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1508 awwwards added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1510 Fix booked card
  frontend/src/style/BookMark.css
  frontend/src/style/Contact.css
Labels: level2, gssoc, Advanced

#1513 Added RubyOnRails for backend Tools
  frontend/src/pages/BackendTools.jsx
Labels: level2, gssoc, Advanced

#1512 Fix contributor's image
  frontend/src/style/About.css
Labels: level2, gssoc, Advanced

#1514 Added .Net technology tool for backend tools
  frontend/src/pages/BackendTools.jsx
Labels: level2, gssoc, Advanced

#1535 fixes #1469
  frontend/src/style/BookMark.css
Labels: level2, gssoc, Advanced

#1560 Added Engage AI
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1544 AI Blog heading is now visible on the page .
  frontend/src/pages/AI.jsx
Labels: level2, gssoc, Advanced

#1572 geeksforgeeks added in coding platforms page
  frontend/src/pages/CodingPlatform.jsx
Labels: level2, gssoc, Advanced

#1563 Title: Hovering effect added to the icons
  frontend/src/Component/Footer.js
  frontend/src/style/Footer.css
Labels: level2, gssoc, Advanced

#1577 Create Animations.css
  frontend/src/style/Animations.css
Labels: level2, gssoc, Advanced

#1578 Added Postman
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1579 Added FOSS United
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1580 Added ICFOSS
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1581 Added element
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1582 Added Simplilearn
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1583 Added NightCafe Creator
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1584 Added Dailymotion
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1585 Added deepbrain ai
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1586 Added invideo
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1587 Added pluralsight
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1588 Added moodle
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1589 Added newton school
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1590 Added mulearn
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1591 Added IEEE
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1592 Added Studocu
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1593 Removed the Overlappings
  frontend/src/style/BackToTopButton.css
Labels: level2, gssoc, Advanced

#1599 Created the social icon hover effect of footer
  frontend/src/Component/Footer.js
  frontend/src/style/Footer.css
Labels: level2, gssoc, Advanced

#1515 Added Laravel technology for backend tools
  frontend/src/pages/BackendTools.jsx
Labels: level2, gssoc, Advanced

#1608 modify chatbot and remove bug
  frontend/src/ChatAssistant/ChatAssistant.css
  frontend/src/ChatAssistant/ChatAssistant.jsx
  frontend/src/ChatBot/config.jsx
  frontend/src/style/Navbar.css
Labels: level2, gssoc, Advanced

#1609 Integrated dockerfile into the project
  README.md
  backend/Dockerfile
  docker-compose.yaml
  frontend/Dockerfile
Labels: level2, gssoc, Advanced

#1621 developed Remote Jobs page
  frontend/src/App.js
  frontend/src/Component/Footer.js
  frontend/src/pages/RemoteJob.jsx
  frontend/src/style/Remotejob.css
Labels: level2, gssoc, Advanced

#1630 The "Rate us" page is working properly.
  frontend/package-lock.json
  frontend/src/Component/Navbar/NavbarCenter.js
  frontend/src/Component/Rate.css
  frontend/src/Component/Rate.js
  frontend/src/Component/Rate.jsx
  frontend/src/style/Footer.css
Labels: level2, gssoc, Advanced

#1627 NewTool: ibomma added to website
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced

#1625 Developed Ui page
  frontend/src/App.js
  frontend/src/Component/Footer.js
  frontend/src/pages/UserInterface.jsx
  frontend/src/style/UserInterface.css
Labels: level2, gssoc, Advanced

#1624 Developed Movies page
  frontend/src/App.js
  frontend/src/Component/Footer.js
  frontend/src/pages/Movies.jsx
  frontend/src/style/Movies.css
Labels: level2, gssoc, Advanced

#1623 Developed Extensions page
  frontend/src/App.js
  frontend/src/Component/Footer.js
  frontend/src/pages/Extensions.jsx
  frontend/src/style/Extension.css
Labels: level2, gssoc, Advanced

#1631 hakerearth codingplatform
  frontend/src/pages/CodingPlatform.jsx
Labels: level2, gssoc, Advanced

#1537 fixes #1466
  frontend/src/pages/CodingPlatform.jsx
Labels: level2, gssoc, Advanced

#1295 Fixed Overlapping
  frontend/src/pages/AI.jsx
  frontend/src/pages/Extension.jsx
  frontend/src/pages/FrontendTools.jsx
  frontend/src/pages/Movie.jsx
  frontend/src/style/EthicalHacking.css
Labels: level2, gssoc, Advanced

#1632 Title:- Amazon Prime Video Added
  frontend/src/DB/product.json
Labels: level2, gssoc, Advanced
